# @Author: JogFeelingVI
# @Date:   2023-10-21 21:40:55
# @Last Modified by:   JogFeelingVI
# @Last Modified time: 2023-10-21 22:00:39
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pyglns_t
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Python script
        run: python glns_test.py

      - name: push GitHub
        run: |
          git config --global user.email lifelse@outlook.com
          git config --global user.name JogFeelingVI
          git add .
          git commit -m "update plns" -a
          git push
