# @Author: JogFeelingVI
# @Date:   2023-05-15 20:24:07
# @Last Modified by:   JogFeelingVI
# @Last Modified time: 2023-05-16 23:53:16
name: Update asset.json
on:
  schedule:
    # Run every day at 12:00 AM
    - cron: "0 1 * * *"
    # - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set timezone
        run: |
          sudo apt-get install -y tzdata
          sudo ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo dpkg-reconfigure -f noninteractive tzdata

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If your script requires any additional libraries, install them here
          # pip install your-required-library

      - name: Run Python script
        run: python generate_asset.py

      - name: Commit and push changes
        run: |
          git config user.name "JogFeelingVI"
          git config user.email "lifelse@outlook.com"
          git add asset.json
          git add README.md
          git commit -m "Update asset.json README.md"
          git push
