# @Author: JogFeelingVI
# @Date:   2023-05-15 20:24:07
# @Last Modified by:   JogFeelingVI
# @Last Modified time: 2023-10-11 21:50:37
name: Update asset.json
on:
  workflow_dispatch
  #schedule:
  # Run every day at 12:00 AM
  # - cron: "0 23 * * *"
  # - cron: "*/15 * * * *"
  # 捣时差 longdon -> shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If your script requires any additional libraries, install them here
          # pip install your-required-library

      - name: Run Python script
        run: python generate_asset.py

      - name: Commit and push changes
        run: |
          git config user.name "JogFeelingVI"
          git config user.email "lifelse@outlook.com"
          git add asset.json
          git add README.md
          git commit -m "Update asset.json README.md"
          git push
