# @Author: JogFeelingVI
# @Date:   2023-05-26 08:56:59
# @Last Modified by:   JogFeelingVI
# @Last Modified time: 2023-05-26 16:27:39
name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update_wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: generated_wiki

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt

      - name: Generate wiki content
        run: |
          # Replace this with the command to generate your wiki content
          python generate_wiki.py

      - name: Commit and push to wiki
        run: |
          cd generated_wiki
          git config --global user.name "JogFeelingVI"
          git config --global user.email "lifelse@outlook.com"
          echo ${{ github.repository }}
          git add .
          git commit -m "Update wiki content (automated)"
          git push
