# @Author: JogFeelingVI
# @Date:   2023-05-26 08:56:59
# @Last Modified by:   JogFeelingVI
# @Last Modified time: 2023-05-26 10:18:13
name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update_wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt

      - name: Generate wiki content
        run: |
          # Replace this with the command to generate your wiki content
          python generate_wiki.py

      - name: Commit and push to wiki
        env:
          WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
        run: |
          git config user.name "JogFeelingVI"
          git config user.email "lifelse@outlook.com"
          # https://github.com/JogFeelingVI/autoasset.wiki.git
          git clone https://x-access-token:${WIKI_TOKEN}@github.com/${{ github.repository }}.wiki.git wiki
          cp -r generated_wiki/* wiki/
          cd wiki
          git add .
          git commit -m "Update wiki content (automated)"
          git push
